CVAE_train \
	--gpu_id 1 \
	--path_save_dir ./outputs/baseline_results_swissroll_plus_mask/ \
	--model_fn CVAE_testbed.models.CVAE_baseline.CVAE \
    --model_kwargs baseline_swissroll_kwargs_with_mask.json \
	--batch_size 64  \
    --num_batches 500  \
    --n_epochs 30 \
    --data_type 'synthetic' \
    --dataloader CVAE_testbed.datasets.swiss_roll.SwissRoll \
    --loss_fn CVAE_testbed.losses.ELBO.synthetic_loss \
    --lr 0.001